services:
  db:
    image: postgres:15
    container_name: mtcg_postgres
    environment:
      POSTGRES_USER: mtcguser
      POSTGRES_PASSWORD: mtcgpassword
      POSTGRES_DB: mtcgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: